drop table if exists location cascade;
drop table if exists category cascade;
drop table if exists sub_category cascade;
drop table if exists item cascade;

CREATE TABLE if not exists location
(
    id          bigint PRIMARY KEY generated by default as identity,
    name        varchar NOT NULL,
    address     varchar NOT NULL,
    description varchar NULL
);

CREATE TABLE if not exists category
(
    id          bigint PRIMARY KEY generated by default as identity,
    name        varchar not null,
    description varchar NULL,
    location_id bigint  NULL,
    FOREIGN KEY (location_id) REFERENCES location (id)

);

CREATE TABLE if not exists sub_category
(
    id          bigint PRIMARY KEY generated by default as identity,
    category_id bigint  NOT NULL,
    name        varchar NOT NULL,
    description varchar NULL,
    FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE if not exists item
(
    id              bigint PRIMARY KEY generated by default as identity,
    name            varchar NOT NULL,
    description     varchar NULL,
    sub_category_id bigint     NOT NULL,
    FOREIGN KEY (sub_category_id) REFERENCES sub_category (id)

);

CREATE TABLE IF not exists package (
    ean Bigint PRIMARY KEY,
    brand Varchar NOT NULL,
    name Varchar NOT NULL,
    size Float,
    unit Varchar,
    material Smallint,
    is_recyclable Boolean,
    material_class Smallint,
    package_weight Float
);