spring:
  main:
    banner-mode: off
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
dotenv:
  enabled: true
  location: classpath:.env
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
