drop table if exists liked_item cascade;
drop table if exists app_user cascade;
drop table if exists brand cascade;
drop table if exists category cascade;
drop table if exists size cascade;
drop table if exists item cascade;
drop table if exists picture cascade;
drop type if exists user_role cascade;
drop type if exists item_status cascade;

create type user_role as enum ('USER', 'ADMIN');
create type item_status as enum ('AVAILABLE', 'UNAVAILABLE', 'SOLD');

create table app_user
(
    id       bigint generated by default as identity primary key,
    username varchar(255) unique not null,
    password varchar(255),
    role     VARCHAR(10)         NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);

create table brand
(
    id   bigint generated by default as identity primary key,
    name varchar(30) not null
);

create table category
(
    id          bigint generated by default as identity primary key,
    name        varchar(30) not null,
    category_id bigint references category
);

create table size
(
    id   bigint generated by default as identity primary key,
    name varchar(15) not null
);

create table item
(
    id          bigint generated by default as identity primary key,
    name        varchar(40)    not null,
    description varchar(150),
    price       numeric(10, 2) not null,
    status      VARCHAR(15)    NOT NULL CHECK (status IN ('AVAILABLE', 'UNAVAILABLE', 'SOLD')),
    brand_id    bigint references brand,
    category_id bigint         not null references category,
    size_id     bigint         not null references size,
    seller_id   bigint         not null references app_user,
    buyer_id    bigint references app_user
);

create table liked_item
(
    id       bigint generated by default as identity primary key,
    buyer_id bigint not null references app_user,
    item_id  bigint not null references item on delete cascade
);

create table picture
(
    id            bigint generated by default as identity primary key,
    item_id       bigint       not null references item on delete cascade,
    file_name     varchar(30)  not null,
    file_location varchar(255) not null
);
